[pytest]
markers = 
    prod_only: tests that are only run if --production flag is used.
    device_w: mark test to only run when a W model device is connected.
    device_s: mark test to only run when an S model device is connected.
    device_needed: mark test to run only when a device is connected.
    tty: requires user input or raspi to run