"""
Endaq Automatic Configuration


Used for Configuring a connected endaq based on a JSON file representation of an endaq configuration.
Can generate this JSON filetype based on a connected endaq's current configuration.

class AutoConfig:

    parameters:
        :translator (dict): Links human-readable sensor names to machine-readable sensor IDs. Should be created from generate_translator() and manually parsed for sensor name accuracy.

    functions:
        apply_config(dev, config_changes: dict):
            Ingest a configuration dictionary (not JSON) and apply changes to device.

        generate_config(dev, output_file_name: str = 'configs/config1.json', n: int = 1):
            Generate JSON file based on the device's current configuration, which can be edited, loaded, and given to apply_config().

        generate_translator(dev):
            Prints the name and ID of sensors found on a connected endaq (param: dev) which are not already represented in the translator. Will fully generate usable names, but they won't be pretty.

        clear_recording_files() -> bool:
            clears the /DATA/RECORD directory on a connected endaq.

        get_temperature(dev) -> float:
            Returns temperature in Celsius of the enDAQ from its last recording.

        unmount():
            Unmounts connected drive. Linux-only.

        enable_automount(enable: bool):
            enables/disables usbmount package in linux

"""

""" 
Example of the JSON representing endaq configurations. These are generated by generate_config and each config can be applied to endaq (after json.load()) by apply_config():
{
  "Device Configuration 1": {           # Each config has a name. They should be individually sent to apply_config(), not the entire file.
    "Device Name": {                    # Name of the setting, matching the translator dictionary.
      "value": "Power Testing Daq",     # Value of setting. In this case, Device Name will be set to "Power Testing Daq"
      "data type": "str",               # The remaining entries help the user input correct data.
      "range [min,max]":                # In this case, range and options are unnecessary. See other settings for examples.
        -Infinity,
        Infinity
      ],
      "options": []
    },
    "25g Accelerometer Sample Rate": {
      "value": 5000,
      "data type": "int",
      "range [min,max]": [
        10,
        20000
      ],
      "options": []
    },
    "Inertial Measurement Acquisition Mode": {
      "value": 0,
      "data type": "int",
      "range [min,max]": [
        -Infinity,
        Infinity
      ],
      "options": {
        "0": "Off",
        "16": "Relative Orientation (Quaternion)",
        "1": "Acceleration",
        "2": "Rotation",
        "3": "Accel, Rot"
      }
    }
}

Actual in-use configs can be found in the /configs directory.
"""


import endaq.device as de
import os, time

# Drive that endaq shows up as (e.g.  D:/ or G:/ )
WIN_PATH_ROOT = 'G'

class AutoConfig:
    # Translates human-readable sensor names into machine-readable ID
    translator = {
        # DEVICE
        'Device Name': 589695,
        'Device Notes': 655231,
        'Custom Recording Tags': 1572735,
        'File Name Style': 1507199,
        'Recording Directory': 1376127,
        'Recording File Prefix': 1441663,
        'Plug-In Action': 720767,
        'Button Mode': 1113983,
        'UTC Offset': 786303,

        # WIFI
        'Wifi Enable': 1638271,
        'Wifi While Asleep': 2686847,
        'Wifi While Triggering': 2752383,
        'Wifi While Recording': 2817919,
        'Wifi Broker IP Address': 2490239,
        'Wifi mDNS Instance Name': 2883455,
        'Wifi Stream Recording Data': 2555775,

        # Triggers
        'Trigger Mode': 1245055,
        'Start at Time': 1048447,
        'Pre-Recording Delay/Interval': 851839,
        'Recording Time Limit': 917375,
        'Recording File Size Limit': 1179519,
        'Retrigger': 982911,
        'Wait for All Sensor Conditions': 1310591,
        'Ctrl Pad Pressure Trigger': 327719,
        'Ctrl Pad Pressure Trigger, Low': 196647,
        'Ctrl Pad Pressure Trigger, High': 262183,
        'Internal Pressure Trigger': 327716,
        'Internal Pressure Trigger, Low': 196644,
        'Internal Pressure Trigger, High': 262180,
        'Ctrl Pad Temperature Trigger': 327975,
        'Ctrl Pad Temperature Trigger, Low': 196903,
        'Ctrl Pad Temperature Trigger, High': 262439,
        'Internal Temperature Trigger': 327972,
        'Internal Temperature Trigger, Low': 196900,
        'Internal Temperature Trigger, High': 262436,
        '25g Acceleration Trigger, Low': 261896,
        '25g Acceleration Trigger, High': 327432,
        '40g Acceleration Threshold': 327504,
        '40g Acceleration Trigger Enable': 393040,

        # Sensors
        '25g Accelerometer XYZ Enable': 130824,
        '25g Accelerometer Sample Rate': 196360,
        '25g Accelerometer Override Antialiasing Filter Cutoff': 589576,
        '40g Accelerometer Enable': 130896,
        '40g Accelerometer Sample Rate': 196432,
        '40g Accelerometer High Pass Filter': 458576,
        '40g Accelerometer Max Range': 589648,
        'Inertial Measurement Acquisition Mode': 130859,
        'Inertial Measurement Orientation Data Rate': 133163,
        'Inertial Measurement Acceleration Data Rate': 131371,
        'Inertial Measurement Rotation Data Rate': 131627,
        'Inertial Measurement Magnetic Field Data Rate': 132139,
        'Ctrl Pad Enable': 130875,
        'Ctrl Pad Sample Rate': 196411,
        'Light Sensor Enable': 130892,
        'Gyroscope Enable': 130900,
        'Gyroscope Sample Rate': 196436,
        'CPG Enable': 130904,
        'GPS Power Btw Recordings': 2162559,
    }

    @staticmethod
    def apply_config(dev: de.Recorder, config_changes: dict) -> None:
        """
        Ingest a configuration dictionary (not JSON) and apply changes to device.

        :param dev: (de.Recorder) device access
        :param config_changes: (dict) configuration data in format {"SETTING_TRANSL_NAME": {'value': VALUE, 'etc': etc... }}. To generate a configuration data file, use AutoConfig.generate_config().
        :return: None
        """
        for raw_name, data in config_changes.items():
            # assert that each item exists and can be linked to a device configuration.
            # Translate Name to config item
            assert raw_name in AutoConfig.translator, f'Invalid Name: "{raw_name}" not in translator'
            id = AutoConfig.translator[raw_name]
            if not AutoConfig.translator[raw_name] in dev.config.items:
                print(f'Invalid Configuration Id: # {id}, "{raw_name}" Not On Device or Incorrect Id')
                continue
            # assert AutoConfig.translator[raw_name] in dev.config.items, f'Invalid Configuration Id: # {id}, "{raw_name}" Not On Device or Incorrect Id'
            my_config_item = dev.config.items[id]

            # Set value in item
            my_config_item.value = data['value']

        # Push to device
        changes = dev.config.getChanges()
        if not changes:
            print('apply_config: No changes made')
            return

        dev.config.applyConfig()

        return changes

    @staticmethod
    def generate_config(dev: de.Recorder, output_file_name: str = 'configs/generated.json', n: int = 1) -> None:
        """
        Generates a configuration JSON based on the device's current state, which can be edited, loaded, and given to apply_config(). Duplicate the config n times in the file.
        :param dev: (endaq.device.Recorder) device reference
        :param output_file_name: Path to output file
        :param n: (int) n copies of JSON are appended to file under a different key.
        :return: A dictionary identical to the output file contents. Represents the current configuration.
        """
        from json import dumps
        output = {}
        for i in range(n):
            sub_config = {}
            for item in dev.config.items.values():
                lookup: list = [n for n, i in AutoConfig.translator.items() if i == item.configId]
                back_translated_name: str = lookup[0] if lookup else None
                if not back_translated_name:
                    continue
                sub_config.update({back_translated_name: {
                    'value': item.value, 'data type': item.dtype.__name__, 'range [min,max]': (item.min, item.max),
                    'options': item.options
                }
                })
            output.update({f'Generated Configuration {i}': sub_config})
        if output_file_name:
            with open(output_file_name, 'w') as my_file:
                my_file.write(dumps(output))
        return output

    @staticmethod
    def generate_translator(dev) -> None:
        """ Prints the name and ID of sensors found on a connected endaq (param: dev) which are not already represented in the translator. Will fully generate usable names, but they won't be pretty. """
        out = {}
        import random as r
        for i in dev.config.items.values():
            id = i.configId
            ch = dev.config._getChannel(id)
            l = i.label
            disp_name = (ch.displayName + ' ' if ch != None else '')
            name = disp_name + (l if l else '')
            if not name: name = 'no name but options: ' + str(i.options)
            if not name:
                name = 'noname' + str(r.randint)
            if id in list(AutoConfig.translator.values()):
                continue
            out[name] = id
        import pprint
        print('add to translator: ')
        pprint.pp(out)
        return out

    @staticmethod
    def clear_recording_files() -> bool:
        """ Clears the /DATA/RECORD directory on a connected endaq. CONFIGURE WIN_PATH_ROOT AS NECESSARY! """
        dir_record = f'{WIN_PATH_ROOT}:/DATA/RECORD' if os.name == 'nt' else r'/media/usb/DATA/RECORD'

        assert os.path.isdir(dir_record), 'clear_rec_files: nonexistent dir'

        for file in os.listdir(dir_record):
            file_path = dir_record + r'/' + file
            os.remove(file_path)
        return True

    @staticmethod
    def get_temperature(dev) -> float:
        """
        Returns temperature in Celsius of the enDAQ from its last recording.
        :param dev: (endaq.device.Recorder) reference to endaq
        """
        import endaq.ide as ide

        # Get Latest file in recording directory
        def newest(path):
            """gets path to most recent file in dir"""
            files = os.listdir(path)
            assert len(files) > 0, 'attempted get_temperature on endaq with no recording files'
            paths = [os.path.join(path, basename) for basename in files]
            return max(paths, key=os.path.getctime)

        path_record = newest(f'{WIN_PATH_ROOT}:/DATA/RECORD' if os.name == 'nt' else r'/media/usb/DATA/RECORD')

        # Use endaq.ide to import file as pd dataframe
        doc = ide.get_doc(path_record)
        df = ide.to_pandas(doc.channels[20])
        doc.close()

        # Get last value in temperature recording
        temp = float(df['Internal Temperature'].iloc[-1])
        return temp

    @staticmethod
    def unmount():
        """ Unmounts connected drive. Linux-only. """
        if os.name != 'posix': return

        os.system('umount /media/usb') # unmount
        os.system('udisksctl power-off -b /dev/sda1') # power down drive. avoids errors
        time.sleep(0.25) # needed?

    @staticmethod
    def enable_automount(enable: bool):
        """ enables/disables usbmount package in linux """
        if os.name != 'posix': return

        with open('/etc/usbmount/usbmount.conf', 'r+') as f:
            f.seek(202)
            f.write('1' if enable else '0')
        with open('/sys/bus/usb/drivers_autoprobe', 'w') as f:
            f.write('1' if enable else '0')




def testing():
    """ Connects to endaq, applies a configuration with main accelerometer ON at 20k Hz. """
    dev = de.getDevices()[0]

    from json import load
    with open('configs/w8_tests/main_accel.json', 'r') as file:
        config = list(load(file).values())[0]

    AutoConfig.apply_config(dev,  config)


if __name__ == '__main__':
    dev = de.getDevices()[0]
    AutoConfig.generate_config(dev)
