# Testing mosquitto configuration, running on localhost
# Running with 'verbose' logging (`-v`) during development/testing is recommended!
listener 1883 0.0.0.0
allow_anonymous true
log_timestamp_format %F_%T
