name: Unit test on push and PR


on: [push, pull_request, workflow_dispatch]


jobs:
  unit-tests:
    name: Run Unit Tests

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']

    env:
      OS: ${{ matrix.os }}
      PYTHON-VERSION: ${{ matrix.python-version }}

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install --upgrade pip

      - uses: actions/checkout@v4

      - run: python -m pip install -r requirements.txt
      - run: python -m pip install pytest pytest-cov mock

      - run: python -m pytest ./tests/

  automated-tests:
    name: Run Automated Device Tests

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.12', '3.13']

    env:
      APPROVED_USERS: '["pscheidler", "StokesMIDE"]'
      VENV_DIR: /opt/runner/venvs/endaq-device/
      PYTHON_VERSION: ${{ matrix.python-version }}

    runs-on: [self-hosted, device-library-tester]
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install --upgrade pip

      - uses: actions/checkout@v4

      - name: Check or create virtual environment
        run: |
          if [ -d ${{ env.FULL_VENV_PATH }} ]; then
            echo "Virtual environment exists in ${{ env.FULL_VENV_PATH }}"
          else
            echo "Creating virtual environment in ${{ env.FULL_VENV_PATH }}"
            python -m venv ${{ env.FULL_VENV_PATH }}
          fi
          
          echo "Activating virtual environment $FULL_VENV_PATH ..."
          source "${{ env.FULL_VENV_PATH }}/bin/activate"
        env:
          FULL_VENV_PATH: ${{ format('{0}_{1}', env.VENV_DIR, env.PYTHON_VERSION) }}
        shell: bash

      - name: Set up libraries
        run: |
          echo "::group::Install main requirements"
          python -m pip install -r requirements.txt
          echo "::endgroup::"
          echo "::group::Instal test_hw requirements"
          python -m pip install -r ./test_hardware/requirements.txt
          echo "::endgroup::"
          echo "::group::Install test specific libraries"
          python -m pip install pytest pytest-cov mock
          echo "::endgroup::"
          echo "::group::Full library list"
          python -m pip list
          echo "::endgroup::"

      - name: Run device tests if pusher is approved
        if: ${{ contains(fromJSON(env.APPROVED_USERS), github.event.pusher.name) }}
        run: python -m pytest --random-order --device "W0018491" --raspi ./test_hardware/
        env:
          GUEST_WIFI_PW: ${{ secrets.GUEST_WIFI_PW }}

      - name: Print IP Address
        if: ${{ contains(fromJSON(env.APPROVED_USERS), github.event.pusher.name) }}
        run: |
          echo "IP=$(hostname -I | awk '{print $1}')"
        shell: bash
