name: Unit test on push and PR


on: [push, pull_request, workflow_dispatch]


jobs:
  unit-tests:
    name: Run Unit Tests

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]

    env:
      OS: ${{ matrix.os }}
      PYTHON-VERSION: ${{ matrix.python-version }}

    runs-on: ${{ matrix.os }}

    steps:

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install --upgrade pip

      - uses: actions/checkout@v2

      - run: python -m pip install -r requirements.txt
      - run: python -m pip install pytest pytest-cov mock

      - run: python -m pytest ./tests/
